[book]
authors = ["g-w1"]
language = "en"
multilingual = false
src = "src"
title = "ez Docs"

[output.html]
default-theme = "dark"
preferred-dark-theme = "ayu"
curly-quotes = true

[build]
build-dir = "docs"
