name: Build/Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: goto-bus-stop/setup-zig@v1
      with:
        version: 0.7.1
    - name: Install Nasm
      run: sudo apt-get install nasm; nasm -v
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose && cd tests && ./test.sh
