name: Build/Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: goto-bus-stop/setup-zig@v1
      with:
        version: master
    - name: Install Nasm
      run: apt-get install nasm
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose && cd tests && ./test.sh
